[project]
name = "ecommerce-oltp-system-data"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Litaaya", email = "minhquans2810@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "faker>=40.39.0",
    "psycopg>=3.3.6",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ecommerce-oltp-system-data = "ecommerce_oltp_system_data:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
